version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-ng
    volumes:
      - challenge-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ng-challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ngchallenge

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    ports:
      - 5555:5555
    environment:
      POSTGRES_URL: postgresql://admin:ngchallenge@postgres:5432/ng-challenge

  backend:
    build: ./Backend
    container_name: backend-ng
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres

  frontend:
    build: ./Frontend
    container_name: frontend-ng
    restart: always
    ports:
      - 8000:80
    links:
      - backend
    depends_on:
      - backend

volumes:
  challenge-data:
