version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres-ng
    volumes:
      - challenge-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ng-challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ngchallenge

  backend:
    build: ./Backend
    container_name: backend-ng
    restart: always
    ports:
      - 8080:8080
    links:
      - "db"
    depends_on:
      - "db"

volumes:
  challenge-data:
